<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class keanggotaanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('keanggotaans')->insert([
            [
                'nama' => 'Ahmad Fauzan',
                'nip_nik' => '198501012010011001',
                'instansi' => 'Dinas Pendidikan Provinsi NTB',
                'kabupaten_kota' => 'Kota Mataram',
                'jabatan' => 'Kepala Bidang',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Mitra Utama',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-01-15',
            ],
            [
                'nama' => 'Siti Rahmawati',
                'nip_nik' => '198702152012022002',
                'instansi' => 'Dinas Pendidikan Kabupaten Lombok Barat',
                'kabupaten_kota' => 'Lombok Barat',
                'jabatan' => 'Koordinator',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Koordinator Mitra',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-02-10',
            ],
            [
                'nama' => 'Muhammad Rizky',
                'nip_nik' => '199003202015031003',
                'instansi' => 'Universitas Mataram',
                'kabupaten_kota' => 'Kota Mataram',
                'jabatan' => 'Dosen',
                'jenis_mitra' => 'Perguruan Tinggi',
                'peran' => 'Mitra Pendidikan',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-02-18',
            ],
            [
                'nama' => 'Dewi Lestari',
                'nip_nik' => '199105052016042004',
                'instansi' => 'Dinas Pendidikan Kabupaten Lombok Tengah',
                'kabupaten_kota' => 'Lombok Tengah',
                'jabatan' => 'Staf',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Anggota',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-03-05',
            ],
            [
                'nama' => 'Budi Santoso',
                'nip_nik' => '198812122014051005',
                'instansi' => 'Dinas Pendidikan Kabupaten Lombok Timur',
                'kabupaten_kota' => 'Lombok Timur',
                'jabatan' => 'Pengawas',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Mitra Daerah',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-03-12',
            ],
            [
                'nama' => 'Nurul Hidayah',
                'nip_nik' => '199206182017062006',
                'instansi' => 'Universitas Hamzanwadi',
                'kabupaten_kota' => 'Lombok Timur',
                'jabatan' => 'Dosen',
                'jenis_mitra' => 'Perguruan Tinggi',
                'peran' => 'Mitra Pendidikan',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-03-20',
            ],
            [
                'nama' => 'Andi Kurniawan',
                'nip_nik' => '198709252013071007',
                'instansi' => 'Dinas Pendidikan Kabupaten Lombok Utara',
                'kabupaten_kota' => 'Lombok Utara',
                'jabatan' => 'Kepala Seksi',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Mitra Daerah',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-04-02',
            ],
            [
                'nama' => 'Rina Marlina',
                'nip_nik' => '199308302018082008',
                'instansi' => 'Sekolah Menengah Atas Negeri',
                'kabupaten_kota' => 'Sumbawa',
                'jabatan' => 'Guru',
                'jenis_mitra' => 'Satuan Pendidikan',
                'peran' => 'Anggota',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-04-10',
            ],
            [
                'nama' => 'Fajar Hidayat',
                'nip_nik' => '198604102011091009',
                'instansi' => 'Dinas Pendidikan Kabupaten Sumbawa',
                'kabupaten_kota' => 'Sumbawa',
                'jabatan' => 'Kepala Bidang',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Mitra Utama',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-04-18',
            ],
            [
                'nama' => 'Maya Sari',
                'nip_nik' => '199211222016102010',
                'instansi' => 'Universitas Teknologi Sumbawa',
                'kabupaten_kota' => 'Sumbawa',
                'jabatan' => 'Dosen',
                'jenis_mitra' => 'Perguruan Tinggi',
                'peran' => 'Mitra Pendidikan',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-05-01',
            ],
            [
                'nama' => 'Hendra Saputra',
                'nip_nik' => '198903152015111011',
                'instansi' => 'Dinas Pendidikan Kabupaten Dompu',
                'kabupaten_kota' => 'Dompu',
                'jabatan' => 'Staf',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Anggota',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-05-08',
            ],
            [
                'nama' => 'Lilis Anggraini',
                'nip_nik' => '199407082019122012',
                'instansi' => 'Sekolah Menengah Pertama Negeri',
                'kabupaten_kota' => 'Dompu',
                'jabatan' => 'Guru',
                'jenis_mitra' => 'Satuan Pendidikan',
                'peran' => 'Anggota',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-05-15',
            ],
            [
                'nama' => 'Arif Maulana',
                'nip_nik' => '198511192010131013',
                'instansi' => 'Dinas Pendidikan Kota Bima',
                'kabupaten_kota' => 'Kota Bima',
                'jabatan' => 'Koordinator',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Koordinator Mitra',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-05-22',
            ],
            [
                'nama' => 'Yuni Kartika',
                'nip_nik' => '199306142018141014',
                'instansi' => 'Universitas Muhammadiyah Bima',
                'kabupaten_kota' => 'Kota Bima',
                'jabatan' => 'Dosen',
                'jenis_mitra' => 'Perguruan Tinggi',
                'peran' => 'Mitra Pendidikan',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-06-03',
            ],
            [
                'nama' => 'Dedi Irawan',
                'nip_nik' => '198807272012151015',
                'instansi' => 'Dinas Pendidikan Kabupaten Bima',
                'kabupaten_kota' => 'Bima',
                'jabatan' => 'Pengawas',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Mitra Daerah',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-06-10',
            ],
            [
                'nama' => 'Fitri Handayani',
                'nip_nik' => '199510052020161016',
                'instansi' => 'Sekolah Dasar Negeri',
                'kabupaten_kota' => 'Bima',
                'jabatan' => 'Guru',
                'jenis_mitra' => 'Satuan Pendidikan',
                'peran' => 'Anggota',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-06-18',
            ],
            [
                'nama' => 'Rudi Hartono',
                'nip_nik' => '198610112011171017',
                'instansi' => 'Dinas Pendidikan Provinsi NTB',
                'kabupaten_kota' => 'Kota Mataram',
                'jabatan' => 'Analis',
                'jenis_mitra' => 'Instansi Pemerintah',
                'peran' => 'Anggota',
                'status' => 'Nonaktif',
                'tanggal_bergabung' => '2024-11-10',
            ],
            [
                'nama' => 'Intan Permata',
                'nip_nik' => '199402192019181018',
                'instansi' => 'Lembaga Pendidikan Masyarakat',
                'kabupaten_kota' => 'Lombok Barat',
                'jabatan' => 'Pengelola',
                'jenis_mitra' => 'Lembaga Pendidikan',
                'peran' => 'Mitra Pendidikan',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-07-02',
            ],
            [
                'nama' => 'Wahyu Setiawan',
                'nip_nik' => '198912242014191019',
                'instansi' => 'Organisasi Pendidikan Daerah',
                'kabupaten_kota' => 'Lombok Tengah',
                'jabatan' => 'Ketua',
                'jenis_mitra' => 'Organisasi',
                'peran' => 'Mitra Strategis',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-07-15',
            ],
            [
                'nama' => 'Salsa Amalia',
                'nip_nik' => '199609302021201020',
                'instansi' => 'Komunitas Pendidikan NTB',
                'kabupaten_kota' => 'Kota Mataram',
                'jabatan' => 'Koordinator',
                'jenis_mitra' => 'Komunitas',
                'peran' => 'Mitra Strategis',
                'status' => 'Aktif',
                'tanggal_bergabung' => '2025-08-01',
            ],
        ]);
    }
}